In [1]:
%matplotlib inline

In [60]:
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np

In [17]:
pd.options.display.max_columns = 50

In [4]:
df = pd.read_csv("dados/casos_coronavirus.csv",encoding='latin')

In [27]:
df.columns

Index(['bairroPaciente', 'classificacaoEstadoSivep', 'codigoMunicipioPaciente',
       'codigoPaciente', 'comorbidadeAsmaSivep',
       'comorbidadeCardiovascularSivep', 'comorbidadeDiabetesSivep',
       'comorbidadeHematologiaSivep', 'comorbidadeImunodeficienciaSivep',
       'comorbidadeNeurologiaSivep', 'comorbidadeObesidadeSivep',
       'comorbidadePneumopatiaSivep', 'comorbidadePuerperaSivep',
       'comorbidadeRenalSivep', 'comorbidadeSindromeDownSivep',
       'dataEntradaUtisSvep', 'dataEvolucaoCasoSivep', 'dataInicioSintomas',
       'dataInternacaoSivep', 'dataNotificacao', 'dataObito',
       'dataResultadoExame', 'dataSaidaUtisSvep', 'dataSolicitacaoExame',
       'estadoPaciente', 'evolucaoCasoSivep', 'idSivep', 'idadePaciente',
       'municipioPaciente', 'obitoConfirmado', 'paisPaciente',
       'resultadoFinalExame', 'sexoPaciente'],
      dtype='object')

In [250]:
dcasos = df[['codigoPaciente','sexoPaciente','municipioPaciente','resultadoFinalExame','dataInicioSintomas','dataNotificacao','dataResultadoExame']]
# dcasos[dcasos['municipioPaciente']=='FORTALEZA'].pivot_table(index=['resultadoFinalExame','municipioPaciente'],aggfunc='count')
# dcasos_aux = dcasos.pivot_table(index=['resultadoFinalExame','municipioPaciente','codigoPaciente'],aggfunc='count').reset_index()

dcasos['dataCasoComputado'] = dcasos['dataInicioSintomas']
dcasos['dataCasoComputado'].fillna(dcasos['dataNotificacao'],inplace=True)
dcasos['dataCasoComputado'].fillna(dcasos['dataResultadoExame'],inplace=True)
dcasos['ano'] = dcasos['dataCasoComputado']
dcasos['ano'] = dcasos['ano'][pd.notnull(dcasos['ano'])].apply(lambda x: int(x[0:4]))
# dcasos['dataCasoComputado'] = dcasos.loc[dcasos['ano']==202,'dataCasoComputado'].apply(lambda x: "2020"+x[4:])
dcasos.loc[dcasos['ano']==202,'dataCasoComputado'] = dcasos.loc[dcasos['ano']==202,'dataCasoComputado'].apply(lambda x: "2020"+x[4:])
dcasos.loc[dcasos['ano']==202,'ano'] = 2020

pd.to_datetime(dcasos['dataCasoComputado'])

/home/davisbarreira/anaconda3/envs/covid19ce/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/home/davisbarreira/anaconda3/envs/covid19ce/lib/python3.7/site-packages/pandas/core/generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)
/home/davisbarreira/anaconda3/envs/covid19ce/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/davisbarreira/anaconda3/envs/covid19ce/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/home/davisbarreira/anaconda3/envs/covid19ce/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

0              NaT
1              NaT
2       2020-03-20
3       2020-03-29
4       2020-03-24
           ...
20130   2020-03-23
20131   2020-03-26
20132   2020-03-21
20133   2020-03-25
20134   2020-03-20
Name: dataCasoComputado, Length: 20135, dtype: datetime64[ns]

/home/davisbarreira/anaconda3/envs/covid19ce/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/home/davisbarreira/anaconda3/envs/covid19ce/lib/python3.7/site-packages/pandas/core/generic.py:6245: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)
/home/davisbarreira/anaconda3/envs/covid19ce/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/home/davisbarreira/anaconda3/envs/covid19ce/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/home/davisbarreira/anaconda3/envs/covid19ce/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [249]:
dcasos[dcasos['ano']==202]
# "2020"+dcasos.iloc[19922]['dataResultadoExame'][4:]
# dcasos.loc[dcasos['ano']==202,'dataCasoComputado'].apply(lambda x: "2020"+x[4:])
# dcasos

,codigoPaciente,sexoPaciente,municipioPaciente,resultadoFinalExame,dataInicioSintomas,dataNotificacao,dataResultadoExame,dataCasoComputado,ano
0,7e2e030aeb821dc31333e4590b9d83f5,FEMININO,NaN,Negativo,NaN,NaN,NaN,NaN,NaN
1,438e3e58edd976ac46cec06e8c17850e,MASCULINO,NaN,Negativo,NaN,NaN,NaN,NaN,NaN
2,583f9182bedd38b50326e1d866bdf4c0,MASCULINO,NaN,Negativo,NaN,NaN,2020-03-20 00:00:00.0,2020-03-20 00:00:00.0,2020.0
3,1aebb3cc91e52b37e2a3d54e05eff098,MASCULINO,NaN,Negativo,NaN,NaN,2020-03-29 00:00:00.0,2020-03-29 00:00:00.0,2020.0
4,0acfa773ece16ff9920cf5616f73ffe8,FEMININO,NaN,Negativo,NaN,NaN,2020-03-24 00:00:00.0,2020-03-24 00:00:00.0,2020.0
...,...,...,...,...,...,...,...,...,...
20130,b90376e69d28b7fed86cf9a8d3d7f32a,FEMININO,NaN,Negativo,NaN,NaN,2020-03-23 00:00:00.0,2020-03-23 00:00:00.0,2020.0
20131,e22cf245b7afae61b26e4885d4d1dd3e,FEMININO,NaN,Negativo,NaN,NaN,2020-03-26 00:00:00.0,2020-03-26 00:00:00.0,2020.0
20132,979bbc2ae610c9dcb53642c1ad4926fb,FEMININO,NaN,Negativo,NaN,NaN,2020-03-21 00:00:00.0,2020-03-21 00:00:00.0,2020.0
20133,fae5a501f57baabfc22aa349a64046cb,MASCULINO,NaN,Negativo,NaN,NaN,2020-03-25 00:00:00.0,2020-03-25 00:00:00.0,2020.0
20134,676f0f92c806380d7d2bca970ce909df,FEMININO,NaN,Negativo,NaN,NaN,2020-03-20 00:00:00.0,2020-03-20 00:00:00.0,2020.0

In [89]:
# pd.isna(dcasos['dataInicioSintomas'])
# dcasos = dcasos[['dataInicioSintomas','dataNotificacao','dataResultadoExame']].fillna("")
# dcasos['dataCasoComputado'] = dcasos['dataInicioSintomas'] + dcasos['dataNotificacao'] + dcasos['dataResultadoExame']

In [53]:
dcasos[dcasos['municipioPaciente']=='FORTALEZA'].pivot_table(index=['resultadoFinalExame','municipioPaciente'],aggfunc=lambda x: len(x.unique()))

,,codigoPaciente,dataInicioSintomas,dataNotificacao,dataResultadoExame,sexoPaciente
resultadoFinalExame,municipioPaciente,,,,,
Em Análise,FORTALEZA,3009,46,193,2,5
Inconclusivo,FORTALEZA,62,15,29,17,2
Negativo,FORTALEZA,4036,44,1278,44,4
Positivo,FORTALEZA,1795,36,411,31,4

In [55]:
dcasos[pd.isna(dcasos['codigoPaciente'])]

Empty DataFrame
Columns: [codigoPaciente, sexoPaciente, municipioPaciente, resultadoFinalExame, dataInicioSintomas, dataNotificacao, dataResultadoExame]
Index: []

In [51]:
dcasos[dcasos['municipioPaciente']=='FORTALEZA']

,codigoPaciente,sexoPaciente,municipioPaciente,resultadoFinalExame,dataInicioSintomas,dataNotificacao,dataResultadoExame
7,6a6b81967f5d385b4c9cb551a4c88040,MASCULINO,FORTALEZA,Em Análise,2020-03-29 00:00:00.0,2020-03-31 00:00:00.0,NaN
8,3baade2ba4ae23f96c4d594d7f3f00fb,FEMININO,FORTALEZA,Em Análise,2020-03-30 00:00:00.0,2020-03-31 00:00:00.0,NaN
9,942078a950f3049737afcd4b0fc2b94f,FEMININO,FORTALEZA,Em Análise,2020-03-30 00:00:00.0,2020-03-31 00:00:00.0,NaN
10,f00aab72ee0a18c2045d6ddcd968c3b3,MASCULINO,FORTALEZA,Em Análise,2020-03-18 00:00:00.0,2020-04-01 00:00:00.0,NaN
12,da42dbe5d4e8c8565acc62ea6de0a2c2,FEMININO,FORTALEZA,Em Análise,2020-03-18 00:00:00.0,2020-03-31 00:00:00.0,NaN
...,...,...,...,...,...,...,...
20092,3eac6bc0a69a96ff35e284ee76007c58,MASCULINO,FORTALEZA,Negativo,NaN,NaN,2020-04-10 00:00:00.0
20093,c430ecc534ef015cc114b3665be9df6c,MASCULINO,FORTALEZA,Negativo,NaN,NaN,2020-04-10 00:00:00.0
20094,f765e47007d6d83d0976c6683abdc6d0,MASCULINO,FORTALEZA,Negativo,NaN,NaN,2020-04-10 00:00:00.0
20105,f84cbafb1af73d1aa46e31903b15d338,FEMININO,FORTALEZA,Negativo,NaN,NaN,2020-04-10 00:00:00.0
20106,1b939a3d06945c0d55df0c741f9f6db4,FEMININO,FORTALEZA,Negativo,NaN,NaN,2020-04-10 00:00:00.0

In [23]:
df.pivot_table(index=['resultadoFinalExame'],aggfunc='count')

,bairroPaciente,classificacaoEstadoSivep,codigoMunicipioPaciente,codigoPaciente,comorbidadeAsmaSivep,comorbidadeCardiovascularSivep,comorbidadeDiabetesSivep,comorbidadeHematologiaSivep,comorbidadeImunodeficienciaSivep,comorbidadeNeurologiaSivep,comorbidadeObesidadeSivep,comorbidadePneumopatiaSivep,comorbidadePuerperaSivep,comorbidadeRenalSivep,comorbidadeSindromeDownSivep,dataEntradaUtisSvep,dataEvolucaoCasoSivep,dataInicioSintomas,dataInternacaoSivep,dataNotificacao,dataObito,dataResultadoExame,dataSaidaUtisSvep,dataSolicitacaoExame,estadoPaciente,evolucaoCasoSivep,idSivep,idadePaciente,municipioPaciente,obitoConfirmado,paisPaciente,sexoPaciente
resultadoFinalExame,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Em Análise,4187,225,4611,4673,97,141,133,96,117,115,99,115,95,107,94,50,22,2198,189,2323,24,13,9,3733,4628,29,225,4611,4628,25,3820,4673
Inconclusivo,85,6,85,85,1,2,1,1,1,1,1,1,1,0,1,2,2,25,6,53,0,82,2,63,85,2,6,77,85,0,66,85
Negativo,6088,236,5411,6216,76,117,102,72,88,87,74,90,68,83,72,50,34,1113,204,3337,12,5677,12,4181,5447,36,236,6009,5444,14,4645,6214
Positivo,2106,258,2116,2152,80,235,223,79,189,187,82,192,71,185,79,114,77,713,235,1346,148,1952,26,1310,2120,96,258,2103,2120,147,1520,2152